server:
  port: ${PORT:443}

  ssl:
    enabled: true
    # keystore format
    key-store-type: PKCS12
    # keystore location
    key-store: classpath:keystore/server.p12
    # keystore password
    key-store-password: changeit

  # SSL protocol to use
    protocol: TLS
  # Enabled SSL protocol

    enabled-protocols: TLSv1.2
    #client-auth: need
    #trust store location
    #trust-store: classpath:keystore/server-truststore.p12
    #trust store password
    #trust-store-password: changeit

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:ch://localhost:8123} #
    username: ${SPRING_DATASOURCE_USERNAME:default}
    password: ${SPRING_DATASOURCE_PASSWORD:ENC(Xj8TLRm6L2Eto5ufBdLQg0MXaEUgtVCXJoGttMLdSJxVUFN+bqEw2/iVD66OP/vp)}
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
 # for swagger-ui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: keenetic

  security:
    jwt:
      jwtSecret: ENC(3DNdSzuVKsOicKHSLgyXFVDP7rD0CVSAS2kzm1rYiMKFEhf/z5RmDHRkT9jwk3Rp)
      jwtExpirationMs: 8640000

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123}

# ips configure
netflow:
  saveFrequencyTime: 10000

  # Свойства, связанные с анализатором пакетов
  analyze:
    routerType: KEENETIC
    analyzeFrequencyMillis: 5000
    updateMeanValueTimeMillis: 600000
    maxUniqueDestinationPortCount: 40
    flowMultiplierLimitation: 20
    # Свойства, связанные с сборщиком пакетом

  router:
    ipAddress: 192.168.1.1
    username: admin
    password: ENC(6bdk1Xm4ha9jye1A7Jp1AFv+Oq3Snl98Isontn4n7pN+Mqam1UWc9s9KoCxdiwzN)
    accessListName: netflow
    collector:
      port: 2055