server:
  port: ${PORT:443}

  ssl:
    enabled: true
    # keystore format
    key-store-type: PKCS12
    # keystore location
    key-store: classpath:keystore/server.p12
    # keystore password
    key-store-password: changeit

  # SSL protocol to use
    protocol: TLS
  # Enabled SSL protocol

    enabled-protocols: TLSv1.2
    #client-auth: need
    #trust store location TODO при деплое папка с сеертификатами должна заливаться отдельно (рядом с jar-ником)
    #trust-store: classpath:keystore/server-truststore.p12
    #trust store password
    #trust-store-password: changeit


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:ch://localhost:8123} #
    username: ${SPRING_DATASOURCE_USERNAME:default}
    password: ${SPRING_DATASOURCE_PASSWORD:ENC(0/obL1mG+pElxepQtZwba9q9eD60e7l2H6gYA2ocMqcWtuP5uSOm743w3N6BEAcB)}
    driverClassName: com.clickhouse.jdbc.ClickHouseDriver
 # for swagger-ui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # liquibase changelog path${JASYPT_ENCRYPTOR_PASSWORD:}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123}

# ips configure
netflow:
  saveFrequencyTime: 10000
  # Свойства, связанные с сборщиком пакетом
  collector:
    routerAddress: 192.168.1.1
    port: 2055
  # Свойства, связанные с анализатором пакетов
  analyze:
    routerType: KEENETIC
    analyzeFrequencyMillis: 5000
    updateMeanValueTimeMillis: 3600000
    maxUniqueDestinationPortCount: 40
    flowMultiplierLimitation: 20

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG