version: '2'

services:
  app:
    build:
      context: ./application
    container_name: app
    ports:
    - 443:443
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:ch://db:8123
    #  - SPRING_DATASOURCE_USERNAME=compose-postgres
    #  - SPRING_DATASOURCE_PASSWORD=compose-postgres
    #  - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    build:
      context: ./db
    ports:
    - 8123:8123
    container_name: db
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin